### ISSUE TITLE
Losing connection can leave you stranded on SerialMonitor

### ISSUE THREAD

**Issue by chipaudette** [Tympan/Tympan_Remote_App#19]
@kxm-creare 

When using the App (BLE), I often include the pre-defined page "SerialMonitor".  I am often watching that page on the App while I'm debugging and changing code on the Tympan.

If I upload new code to the Tympan, it resets the device, which resets the BLE connection to the phone.  The App senses this.  All of the user-defined pages then disappear.  The SerialMonitor page does not disappear.   Fine.

The problem is that you are now orphaned on the SerialMonitor page.  You can't get back to the gear page to reconnect.  Tap on the gear all you want, it doesn't bring you back to the gear page.

You end up having to quite the App and restart.  This is annoying and not what the user expects.

The idea behavior would be for, if the system detects the BLE being disconnected, it jumps itself back to the gear page.

**Comment by kxm-creare** [comment]
The app now jumps back to the "connect" page when it learns that the BLE has been disconnected.
